### ISSUE TITLE
Error: Can't initialize nvrm channel Error: 

### ISSUE THREAD

**Issue by eusoubrasileiro** [jocover/jetson-ffmpeg#119]
After a clean install using a  [custom jetson-nano image](https://github.com/pythops/jetson-nano-image).
That image is simple based on a pure [L4T (linux tegra) version 32.7.1](https://developer.nvidia.com/embedded/linux-tegra-r3271).
After sucessfully building this `jetson-ffmpeg` and simple starting it for the first time I got the following errors. 

```
Error: Can't initialize nvrm channel Error: 
Can't initialize nvrm channel 
Couldn't create ddkvic Session: 
Cannot allocate memory nvbuf_utils: 
Could not create Default NvBufferSession
```

Any clues what am I missing?

**Comment by eusoubrasileiro** [comment]
So it was that I was missing to install ... 

`nvidia-l4t-jetson-multimedia-api` package

After installing errors disappeared!

**Comment by ByerRA** [comment]
I am experiencing the same issue and I have confirmed that I have the "nvidia-l4t-jetson-multimedia-api" installed so this solution didn't work for me.

**Comment by eusoubrasileiro** [comment]
@ByerRA well it seams that now I am facing the same issue after installing the same package...

**Comment by ByerRA** [comment]
> @ByerRA well it seams that now I am facing the same issue after installing the same package...

To prevent "Could not create Default NvBufferSession" errors add the user(s) running FFMPEG to the "video" group then logout and back in.

sudo usermod -aG video <username>

This solved the issue for me.

**Comment by eusoubrasileiro** [comment]
@ByerRA hey just figured out almost in sync with you thanks anyway!
