### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by cgutman** [jocover/jetson-ffmpeg#30]
I noticed this code is missing a license. Can you please add a license file to the repository so the code can be legally used and redistributed?

As stated on https://choosealicense.com/no-permission/:
> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

**Comment by jocover** [comment]
Thank you for your advice,I added MIT License

**Comment by cgutman** [comment]
Thanks, looks good.
