### ISSUE TITLE
could not play main profile stream from Hikvision

### ISSUE THREAD

**Issue by bellkin** [jocover/jetson-ffmpeg#31]
Both stream are recorded from Hikvision DS-2CD3955FWD-IWS(not start with iframe)
1. for H264, gstreamer play rtsp with heavy frame drop, probably timing bug, but play file is fine.
2. for HEVC stream, gstreamer play both rtsp/file fine.
https://www.mediafire.com/folder/8lq8sdsixr1yd/

**Comment by bellkin** [comment]
Conditions tested:
1. Not work with any resolution: 1280x960,2048x1536,2560x1920.
2. Not work with color space change to YUV420:
perl -pe 's/\x{CF}\x{F8}\x{0B}\x{70}/\x{CF}\x{F8}\x{0B}\x{50}/g' < h264er.mp4 > h264nr.mp4
3. Not work with NV12 output.
error message:
NvDdkVicConfigure Failed
nvbuffer_transform Failed

**Comment by st7109** [comment]
should add support about AV_PIX_FMT_YUVJ420P...just same as AV_PIX_FMT_YUV420P

**Comment by bellkin** [comment]
fixed by simply update header files as:
https://github.com/jocover/jetson-ffmpeg/issues/32#issuecomment-625543955
