### ISSUE TITLE
Can jetson tx2 compile jetson-ffmpeg

### ISSUE THREAD

**Issue by honggesmile** [jocover/jetson-ffmpeg#56]
first , thanks for your work,this is great.
Now i comlile this on my jetson tx2. when i run `./configure --enable-nvmpi` 
error appears:
```
`ERROR: nvmpi not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
`
```

I tried to find nvmpi in the system,  
When I type   `pkg-config --list-all | grep nvmpi`   in the command line，
`nvidia@nvidia:~/jetsonTX2-ffmpeg/ffmpeg$ pkg-config --list-all | grep nvmpi
nvmpi                            nvmpi - nvidia multimedia api
`

I  cannot find any solutions,can you give me some advices.thanks for your help.

**Comment by pzhu10** [comment]
you should config the  nvmpi.pc file to pkg-config path
like this：
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
generally speaking ，if you make install jetson-ffmpeg correctly, this will be already set

![image](https://user-images.githubusercontent.com/11349256/95725438-3e0dd680-0caa-11eb-8ea8-f723972acf0d.png)

you can compile jetson-ffmpeg again,
hope useful for you, lucky~~

**Comment by honggesmile** [comment]
it works,thanks very much.
