### ISSUE TITLE
about zerolatency option

### ISSUE THREAD

**Issue by st7109** [jocover/jetson-ffmpeg#7]
Hello, Sir,
I want to try low lentency encoding, I modify "num_capture_buffers" to 5 or less,,ffmpeg will crash. After tested it, must set to 10 or more...could you share some info about this?

**Comment by jocover** [comment]
https://github.com/jocover/jetson-ffmpeg/commit/678107dcdb293425d1969d7e83e4a34caeee823d
encoder num_capture_buffers parameter range 1-32 now
