### ISSUE TITLE
New nvmpi patch, that forces decoders.

### ISSUE THREAD

**Issue by GavinDarkglider** [jocover/jetson-ffmpeg#81]
This is not something I plan on merging, mainly because in its current implementation, it will break decoders if the patch was applied, and nvmpi was not enabled, or it wasnt for a jetson-ffmpeg supported platform.

All this patch does, is what the other one does, but when apps request decoder by name or id, and they are for the generic software decoder/encoder it forces ffmpeg to switch to return the nvmpi decoders/encoders. Patch included as txt file, github doesnt like patch files

Also, It should be mentioned, if your app does any type of sandboxing(Chrome/Firefox) and this is properly installed system wide, with the old ffmpeg stuff removed, you will need to disable that, or the page will crash, or the app you have running in a sandbox.

Also, this might need adjustments to force pix fmt on encoders, as I only previously patched that issue for the decoder.

[ffmpeg_nvmpi.txt](https://github.com/jocover/jetson-ffmpeg/files/6361117/ffmpeg_nvmpi.txt)

**Comment by hax0rsaw** [comment]
I assume the steps for patching this are the same as the other nvpmi patch? When I attempt this - I have errors....

**Comment by GavinDarkglider** [comment]
I might have rebased the patch on a different version of ffmpeg for lakka/libreelec builds I am working on for the switch, It should be the same, that is 4.4(4.0.4? I would have to check) with a bunch of patches for kodi.

**Comment by GavinDarkglider** [comment]
Have a better way to do this, will pr once I have all of the changes orgainzed.
